baseURL: https://cobbing.dev/
languageCode: en-us
title: cobbing.dev
theme: charlolamode
paginate: 5

menu:
    main:
        # - name: Contact
        #   url: /contact/
        #   weight: 30
        # - name: Articles
        #   url: /articles/
        #   weight: 20
        - name: Projects
          url: /project/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs



params:
    author:


    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    hideFooter: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Matthew Cobbing
        description: |

          Techincal Lead at Perkbox
        imageUrl: "/images/profile.png"
        imageTitle: my image
        imageWidth: 240
        imageHeight: 240
        buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: email
          url: "mailto:matthew@cobbing.dev"
        - name: github
          url: "https://github.com/cobbinma"
        - name: linkedin
          url: "https://www.linkedin.com/in/cobbing/"
        - name: medium
          url: "https://medium.com/@cobbinma"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

